modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "edoraworld"
version = "${version}"
displayName = "EdoraWorld"
authors = "Me!"
description = '''
A mod for an RPG experience in Minecraft across the World of Edora
'''
#logoFile = ""

[[dependencies.edoraworld]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.edoraworld]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.edoraworld]]
modId = "architectury"
type = "required"
versionRange = "[11.0.11,)"
ordering = "AFTER"
side = "BOTH"